### ISSUE TITLE
Update npm published package

### ISSUE THREAD

**Issue by piranna** [JoshuaKGoldberg/package.json-validator#75]
NPM latest version is 6 years old, can we get published a new one with latest code?

**Comment by JoshuaKGoldberg** [comment]
Working on this now - expect something Soon ™️ ! 🙌

**Comment by JoshuaKGoldberg** [comment]
Notes:
* 0.6.3 was published 1/8/2018
* Commits since then: b8e9488, 53fa065, e09d248, 2b46255, f1fe16c, 6b858a4, 8e16702, 8f8cb16, 2849c53, bd69f78, b6e9cf7, 3ffb156
* None of those commits have any user-facing features or fixes, just docs - so this will be a patch release

**Comment by JoshuaKGoldberg** [comment]
[`package-json-validator@0.6.4`](https://www.npmjs.com/package/package-json-validator/v/0.6.4) is now published on npm. Note that it's purely a docs touchup to improve the published README.md and repository metadata. I'll push more versions soon that include actual features and fixes. Cheers! 🧡
