### ISSUE TITLE
🚀 Feature: Switch from optimist (deprecated) to yargs

### ISSUE THREAD

**Issue by altano** [JoshuaKGoldberg/package.json-validator#86]
We don't need to get into a conversation about whether [warnings like this](https://github.com/altano/npm-packages/security/dependabot/106) are helpful or not, but they are happening.

My latest one was from pulling in `eslint-plugin-package-json`, because of this dependency chain:

```
eslint-plugin-package-json 0.12.0
└─┬ package-json-validator 0.6.3
  └─┬ optimist 0.6.1
    └── minimist 0.0.10
```

It looks like package-json-validator would benefit from either moving from optimist (deprecated) to directly using an updated version of minimist or switching to something like yargs.

**Comment by de-don** [comment]
+1

**Comment by JoshuaKGoldberg** [comment]
Oop, sorry for the delay! Agreed. Using deprecated dependencies isn't good. 

Per https://www.npmjs.com/package/optimist:

> I don't want to maintain this module anymore since I just use [minimist](https://npmjs.org/package/minimist), the argument parsing engine, directly instead nowadays.
>
> See [yargs](https://github.com/chevex/yargs) for the modern, pirate-themed successor to optimist.

`minimist` does a good bit less than what this currently uses `optimist` for. So I'd say let's move to `yargs`. 👍 accepting PRs!

**Comment by de-don** [comment]
@JoshuaKGoldberg I have opened PR, please check it :)

**Comment by JoshuaKGoldberg** [comment]
Great! I get a notification for every comment, issue, and PR in this repo - so any PR that gets sent effectively tags me. I'll look soon!
